# Generated by Django 3.2.7 on 2022-03-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='楼栋名称')),
                ('house_num', models.CharField(max_length=4, verbose_name='楼栋住房数')),
                ('stated', models.SmallIntegerField(choices=[(0, '未开盘'), (1, '已开盘')], verbose_name='楼栋开盘状态')),
            ],
            options={
                'verbose_name': '小区楼栋',
                'verbose_name_plural': '小区楼栋',
                'db_table': 'village_building',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(max_length=8, verbose_name='房号')),
                ('house_type', models.CharField(max_length=16, verbose_name='住房户型')),
                ('area', models.IntegerField(default=0, verbose_name='占地面积(m²)')),
                ('sale', models.CharField(max_length=16, verbose_name='售价(元/m²)')),
                ('stated', models.SmallIntegerField(choices=[(0, '未售出'), (1, '已售出')], verbose_name='住房售出状态')),
                ('household', models.CharField(max_length=128, null=True, verbose_name='户主id')),
                ('uni', models.CharField(max_length=16, verbose_name='住房所在单元')),
                ('building', models.CharField(max_length=16, verbose_name='住房所在楼栋')),
            ],
            options={
                'verbose_name': '楼栋列表',
                'verbose_name_plural': '楼栋列表',
                'db_table': 'village_house',
            },
        ),
    ]
